module AssetAggregator
  module OutputHandlers
    # An #AssetAggregator::Core::OutputHandler that writes output in a verbose,
    # documented form that's compatible with CSS.
    class CssOutputHandler < AssetAggregator::Core::OutputHandler
      def start_all
        out.puts <<-END
/************************************************************************
 * '#{subpath}.css'
 *
 * This file is GENERATED by the AssetAggregator; do not edit it.
 * This version was generated at #{Time.now}
 ************************************************************************/
END
      end

      def start_aggregator(aggregator)
        out.puts <<-END


/************************************************************************
 * #{aggregator}
 ************************************************************************/

END
      end
      
      def start_fragment(aggregator, fragment)
        out.puts <<-END
/* ----------------------------------------------------------------------
   - #{fragment.source_position}
   ---------------------------------------------------------------------- */
END
      end
    end
  end
end
